## Emacs, make this -*- mode: sh; -*-
### RNEURO
FROM muschellij2/rneuro_ants

#####################
# Getting MALF stuff
#####################
RUN r -e 'devtools::install_github("muschellij2/malf.templates")'



