## Emacs, make this -*- mode: sh; -*-
### RNEURO
FROM rneuro_base

#####################
# Getting MALF stuff
#####################
RUN r -e 'devtools::install_github("muschellij2/malf.templates")'



