## Emacs, make this -*- mode: sh; -*-
### RNEURO
FROM muschellij2/rneuro_ants

RUN git clone https://github.com/muschellij2/imaging_in_r.git

RUN bash
# RUN r -e 'devtools::install_github("muschellij2/ms.lesion")'
